#!/usr/bin/env python3
"""Save usable runners from a check-runners report and sync the web terminal options.

Usage:
  sync-runners.py --report report.json [--out .github/runners.json]
                  [--workflow .github/workflows/web-terminal.yml]

The workflow file must contain a block like:

        # runners:begin
        options:
          - ubuntu-latest
        default: ubuntu-latest
        # runners:end

Everything between the markers is regenerated.
"""
import argparse
import json
import os
import re
from datetime import datetime, timezone

SHELL_OS = ("Linux", "macOS")
PREFERRED_DEFAULT = "ubuntu-latest"


def load_usable(report_path):
    rows = json.load(open(report_path, encoding="utf-8"))
    usable = []
    for r in rows:
        p = r.get("probe")
        if not p:
            continue
        usable.append(
            {
                "label": r["label"],
                "image": r.get("image"),
                "status": r.get("status"),
                "os": p.get("os"),
                "runner_os": p.get("runner_os"),
                "arch": p.get("runner_arch") or p.get("machine"),
                "cpu_model": p.get("cpu_model"),
                "cpu_count": p.get("cpu_count"),
                "memory_gb": p.get("memory_gb"),
                "disk_total_gb": p.get("disk_total_gb"),
                "disk_free_gb": p.get("disk_free_gb"),
                "image_version": p.get("image_version"),
                "kvm": p.get("kvm"),
                "gpu": p.get("gpu"),
                "in_container": p.get("in_container"),
                "tools": p.get("tools") or {},
            }
        )
    return usable


def shell_labels(usable):
    return [
        r["label"]
        for r in usable
        if r["runner_os"] in SHELL_OS and not r["in_container"]
    ]


def update_workflow(path, labels):
    text = open(path, encoding="utf-8").read()
    pattern = re.compile(r"^([ \t]*)# runners:begin.*?^[ \t]*# runners:end[^\n]*", re.S | re.M)
    match = pattern.search(text)
    if not match:
        raise SystemExit(f"runners:begin / runners:end markers not found in {path}")
    indent = match.group(1)
    default = PREFERRED_DEFAULT if PREFERRED_DEFAULT in labels else labels[0]
    block = [f"{indent}# runners:begin (generated by check-runners, do not edit by hand)"]
    block.append(f"{indent}options:")
    block += [f"{indent}  - {label}" for label in labels]
    block.append(f"{indent}default: {default}")
    block.append(f"{indent}# runners:end")
    new_text = text[: match.start()] + "\n".join(block) + text[match.end():]
    if new_text != text:
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(new_text)
        return True
    return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True)
    parser.add_argument("--out", default=".github/runners.json")
    parser.add_argument("--workflow")
    args = parser.parse_args()

    usable = load_usable(args.report)
    if not usable:
        raise SystemExit("No usable runners in report, refusing to overwrite")

    run_url = None
    if os.environ.get("GITHUB_RUN_ID"):
        run_url = "{}/{}/actions/runs/{}".format(
            os.environ.get("GITHUB_SERVER_URL", "https://github.com"),
            os.environ.get("GITHUB_REPOSITORY"),
            os.environ["GITHUB_RUN_ID"],
        )

    labels = shell_labels(usable)
    data = {
        "updated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_run": run_url,
        "web_terminal_labels": labels,
        "runners": usable,
    }
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"Saved {len(usable)} usable runners to {args.out}")

    if args.workflow:
        if not labels:
            raise SystemExit("No Linux/macOS runners available for the web terminal")
        changed = update_workflow(args.workflow, labels)
        print(f"{'Updated' if changed else 'Unchanged'} options in {args.workflow}: {', '.join(labels)}")


if __name__ == "__main__":
    main()
