#!/usr/bin/env python3
"""Write usable runners from a check-runners report into the Web Terminal dropdown.

Usage: sync-runners.py --report report.json --workflow .github/workflows/web-terminal.yml

The workflow file must contain a block like:

        # runners:begin
        options:
          - ubuntu-latest
        default: ubuntu-latest
        # runners:end

Everything between the markers is regenerated. Only Linux / macOS full VMs are
kept (ubuntu-slim is a container with a 15 minute job limit).
"""
import argparse
import json
import re

SHELL_OS = ("Linux", "macOS")
PREFERRED_DEFAULT = "ubuntu-latest"


def usable_runners(report_path):
    rows = json.load(open(report_path, encoding="utf-8"))
    result = []
    for r in rows:
        p = r.get("probe")
        if not p or p.get("runner_os") not in SHELL_OS or p.get("in_container"):
            continue
        result.append((r["label"], p))
    return result


def spec(p):
    parts = [
        p.get("os") or "",
        (p.get("runner_arch") or p.get("machine") or "").lower(),
        f"{p.get('cpu_count')}C",
        f"{p.get('memory_gb')}G RAM",
        f"{p.get('disk_free_gb')}G free",
    ]
    if p.get("kvm"):
        parts.append("KVM")
    if p.get("gpu"):
        parts.append("GPU")
    return ", ".join(x for x in parts if x)


def update_workflow(path, runners):
    text = open(path, encoding="utf-8").read()
    pattern = re.compile(r"^([ \t]*)# runners:begin.*?^[ \t]*# runners:end[^\n]*", re.S | re.M)
    match = pattern.search(text)
    if not match:
        raise SystemExit(f"runners:begin / runners:end markers not found in {path}")
    indent = match.group(1)
    labels = [label for label, _ in runners]
    default = PREFERRED_DEFAULT if PREFERRED_DEFAULT in labels else labels[0]
    width = max(len(label) for label in labels)

    block = [f"{indent}# runners:begin (generated by Check Runners, do not edit by hand)"]
    block.append(f"{indent}options:")
    block += [f"{indent}  - {label:<{width}}  # {spec(p)}" for label, p in runners]
    block.append(f"{indent}default: {default}")
    block.append(f"{indent}# runners:end")

    new_text = text[: match.start()] + "\n".join(block) + text[match.end():]
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(new_text)
    return labels


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True)
    parser.add_argument("--workflow", required=True)
    args = parser.parse_args()

    runners = usable_runners(args.report)
    if not runners:
        raise SystemExit("No usable Linux/macOS runners in report, refusing to overwrite")
    labels = update_workflow(args.workflow, runners)
    print(f"Web Terminal options ({len(labels)}): {', '.join(labels)}")


if __name__ == "__main__":
    main()
